Embedded/Embedded/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),
    path('summernote/', include('django_summernote.urls')),
  
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Embedded/Main/urls.py
from django.urls import path
from Main.views import *
from Main import views

app_name = 'main'
urlpatterns = [
    path('', Main.as_view(), name="main"),
    path('members/', views.ViewMembers, name="Viewmembers"),
    path('mypage/', views.mypage, name="mypage"),
    path('user/edit/', views.editUser, name="edit-user"),
    path('register/', views.register, name="register"),
    path('ajax/idCheck/', views.isExistsID, name='check-id'),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),
    path('board/', ViewBoard.as_view(), name="board"),
    path('board/write/', WriteBoard.as_view(), name="write-board"),
    path('board/<b_id>/', views.readBoard, name='read-board'),
    path('board/<pk>/edit/', EditBoard.as_view(), name="edit-board"),
    path('board/<b_pk>/delete', views.DeleteBoard, name="del-board"),
    path('ajax/file/<pk>/delete', views.delFileWithAjax, name="del-file-ajax"),
    path('board/search', views.searchBoard, name="search-board"),
    path('guestbook/', views.guestbook, name="guestbook"),
    path('ajax/guestbook/', views.ajaxguestbook, name="guestbook-ajax"),
    path('guestbook/write/', views.guestbookWrite, name="guestbook-write"),
    path('schedule/add', views.addSchedule, name="add-schedule")
]

Embedded/Main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

def save_pic_user(instance, name):
    return "{0}/{1}".format("Profile", name)


class RankPicture(models.Model):
    r_rankcode = models.CharField(max_length=5)
    r_images = models.ImageField(null=True)

class Profile(models.Model):
    p_user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    p_name = models.CharField(max_length=5, verbose_name="이름")
    p_grade = models.CharField(max_length=1, verbose_name="학년")
    p_rank = models.CharField(default="재학생", max_length=5, verbose_name="신분", choices=(('재학생', '재학생'), ('졸업생', '졸업생'), ('실장', '실장')))
    p_rank_pic = models.OneToOneField("Main.RankPicture", verbose_name="계급 사진", on_delete=models.DO_NOTHING, null=True)
    p_birth_date = models.DateField(verbose_name="생년월일", null=True)
    p_picture = models.ImageField(verbose_name="사진", null=True, upload_to=save_pic_user)

    


class Board(models.Model):
    b_title = models.CharField(max_length=50, verbose_name="제목")
    b_category = models.CharField(max_length=5, choices=(('정보', '정보'), ('기타', '기타') ), verbose_name="분류", default="정보")
    b_content = models.CharField(max_length=300, verbose_name="내용")
    b_date=models.DateTimeField(auto_now_add=True, verbose_name="작성일", null=True)
    b_user=models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="작성자", null=True)
    b_isNotice = models.BooleanField(default=False, verbose_name="공지 여부")

class Schedule(models.Model):
    s_user = models.CharField(max_length=50)
    s_date = models.DateTimeField(null=True)
    s_finished_date = models.DateTimeField(null=True)
    s_content = models.CharField(max_length=50)



class BoardFiles(models.Model):
    b_board = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)
    b_file = models.FileField(verbose_name="파일", upload_to="Board")
    
class GuestBook(models.Model):
    g_name = models.CharField(max_length=5)
    g_email = models.CharField(max_length=30)
    g_title = models.CharField(max_length=20)
    g_content = models.CharField(max_length=50)
    g_date = models.DateTimeField(auto_now_add=True)
    g_ip = models.CharField(max_length=20)

  

Embedded/Main/forms.py
from django import forms
from Main.models import *
from django.contrib.auth.models import User
from django.forms import inlineformset_factory
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
import re
def name_validator(name):
    regex = re.compile(r'^[가-힣]{2,4}$')
    if regex.search(name):
        print("오케이")

class RegisterForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['p_user', 'p_rank_pic']
        widgets  = {'p_grade' : forms.Select(choices=[('1', '1'), \
            ('2', '2'), ('3', '3'), ('4', '4')]),
            'p_birth_date' : forms.TextInput(attrs={'placeholder' : 'YYYY-MM-dd'})
        }

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['p_picture'].required = False


# 1:1 중 Profile에 대해 만듦
class EditProfile(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['p_user', 'p_rank_pic']
        widgets  = {'p_grade' : forms.Select(choices=[('1', '1'), \
            ('2', '2'), ('3', '3'), ('4', '4')]),
            'p_birth_date' : forms.TextInput(attrs={'placeholder' : 'YYYY-MM-dd'})
        }

    def __init__(self, *args, **kwargs):
        context = super(EditProfile, self).__init__(*args, **kwargs)
        self.fields['p_picture'].required = False
        return context
    

class EditUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']
  
class RegisterForm1(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'password' : forms.PasswordInput(),
              }
        labels = {'username' : '아이디', 'email' : '이메일'}
        help_texts = {'username' : '150이하 문자 입력해 주세요.', }

class BoardForm(forms.ModelForm):
    files = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required=False)
    class Meta:
        model = Board
        exclude = ['b_user', ]
        widgets = {
            'b_content': SummernoteWidget(attrs={'summernote' : \
                    {'lang' : 'ko-KR', 'width' : '100%'},   
                }),
            'b_title' : forms.TextInput(attrs={"size" : "100%"})
        }
        
    

Embedded/Main/views.py
from django.shortcuts import render, redirect, render_to_response, HttpResponse
from django.views.generic import View, ListView, FormView
from django.views.generic.edit import UpdateView, DeleteView
from Main.forms import *
from Main.models import *
import json
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory, inlineformset_factory
# Create your views here.

# 로긴 믹스인
class LoginRequireMixin(object):
    @classmethod
    def as_view(cls, **kwargs):
        view = super(LoginRequireMixin, cls).as_view(**kwargs)
        return login_required(view)

class Main(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'Main/index.html', { })
    
    def post(self, request, *args, **kwargs):
        from django.core import serializers
        sche = serializers.serialize("json", Schedule.objects.all(), ensure_ascii=False,  fields=('s_content', 's_date', 's_user', 's_finished_date'))
        return HttpResponse(json.dumps({"sche" : sche}), content_type="application/json")
    


class Login(View):
    def get(self, request, *args, **kwargs):
        print(request.GET.get("next"))
        return render(request, 'Main/login.html', {'next' : request.GET.get('next')})

    def post(self, request, *args, **kwargs):
        user_id = request.POST.get('id')
        user_pw = request.POST.get('pw')
        try:
            user = User.objects.get(username=user_id)
        except Exception:
            return render(request, 'Main/login.html', {'msg' : '잘못된 아이디입니다.', })
        
        if user.password != user_pw:
            return render(request, 'Main/login.html', {'msg' : '비밀번호가 틀립니다.', })

        login(request, user)

        return redirect(request.GET.get('next', '/'))

@login_required        
def mypage(request):
    return render(request, "Main/mypage.html", {})

@login_required
def editUser(request):
    if request.method == 'POST':
        f1 = EditProfile(request.POST, request.FILES, instance=Profile.objects.get(p_user=request.user))
        f2 = EditUser(request.POST, request.FILES, instance=request.user)

        if f1.is_valid() and f2.is_valid():
            f2.save()
            f1.p_user = f2
            f1.save()
            return redirect('/mypage/')   
    else:
        f1 = EditProfile(instance=Profile.objects.get(p_user=request.user))
        f2 = EditUser(instance=request.user)
    return render(request, "Main/user_edit.html", {
        "f1" : f1, "f2" : f2})

class Logout(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('/')

def file_save_handler(filedatas, instance):
    for f in filedatas:
        BoardFiles.objects.create(
            b_board= instance,
            b_file = f
        )

class WriteBoard(LoginRequireMixin, FormView):
    form_class = BoardForm
    template_name = "Main/board_write.html"
    success_url = "/board/"

    def form_valid(self, form):
        form.instance.b_user = self.request.user
        form.save()
        if self.request.FILES.getlist('files'):
            file_save_handler(self.request.FILES.getlist('files'), form.instance)
        return super(WriteBoard, self).form_valid(form)
        
class EditBoard(UpdateView):
    model = Board
    form_class = BoardForm
    template_name = 'Main/board_edit.html'
    success_url = '/board/'

    def form_valid(self, form):
        boardfiles = form.instance.boardfiles_set.all()
        if self.request.FILES.getlist('files'):
            file_save_handler(self.request.FILES.getlist('files'), form.instance)
        return super(EditBoard, self).form_valid(form)

    def get_initial(self):
        board = self.get_object() # get_object()를 통하여 해당 폼의 대상 객체 추출 가능
        print(board.boardfiles_set.all()) # 보안상 파일은 inital이 안 된다고 함.
        return { 'b_files' :  board.boardfiles_set.all() }
    
    # 그럼, 콘텍스트로 URL을 보내 삭제할 수 있도록 해보자.
    def get_context_data(self, **kwargs):
        context = super(EditBoard, self).get_context_data(**kwargs)
        context['o_files'] = self.get_object().boardfiles_set.all()
        return context

def delFileWithAjax(request, pk):
    if request.method == 'POST':
        try:
            a = BoardFiles.objects.get(id=pk)
            a.delete()
            msg = "삭제가 완료 되었습니다."
        except Exception:
            msg = "삭제 도중 오류가 발생했습니다."
        context = {"msg" : msg,}
        return HttpResponse(json.dumps(context), content_type="application/json")

def DeleteBoard(request, b_pk):
    Board.objects.get(id=b_pk).delete()
    return redirect('/board/')

def searchBoard(request):
    page_ = request.GET.get("page", None)
    keyword = request.GET.get("keyword")
    notice_board = Board.objects.filter(b_isNotice=True)[:5]
    res = Board.objects.filter(Q(b_title__icontains=keyword)|Q(b_user__profile__p_name=keyword), b_isNotice=False)
    p = Paginator(res, 10)
    # 키워드 검색 후 페이지네이션에 따른 보여줄 리스트
    if page_:
        viewing_list = p.page(page_).object_list
        paginator_obj = p.page(page_)
    else:
        viewing_list = p.page(1).object_list
        paginator_obj = p.page(1)
    return render(request, "Main/board.html", {
        "boards" : viewing_list, 'p' : paginator_obj,
        'keyword' : keyword,
        "notice" : notice_board
        })

class ViewBoard(ListView):
    template_name = 'Main/board.html'
    context_object_name = 'boards'
    paginate_by = 10
    
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["notice"] = Board.objects.filter(b_isNotice=True)[:5]
        return data

    def get_queryset(self):
        return Board.objects.filter(b_isNotice=False).order_by('-b_date')

@login_required
def readBoard(request, b_id):
    board = Board.objects.get(id=b_id)

    return render(request, "Main/read_borad.html", {
        'board' : board,
        'files' : board.boardfiles_set.all()
    })


@login_required
def ViewMembers(request):

    mems = User.objects.filter(profile__p_rank="재학생")
    graduate_mems = User.objects.filter(profile__p_rank="졸업생")
    print(mems)
    return render(request, 'Main/Introduction_members.html', {'mems' : mems, 'gra_mems' : graduate_mems})

# 일정 추가
@login_required
def addSchedule(request):
    if request.method == 'POST':
        person = request.POST.get('person')
        date = request.POST.get('date')
        finishdate = request.POST.get('finishdate', None)
        content = request.POST.get('content')
        data = {'s_user' : person, 's_date' : date ,'s_content' : content}
        print(finishdate)
        if finishdate:
            data['s_finished_date'] = finishdate
        Schedule.objects.create(**data)
        return HttpResponse("<script>alert('저장 완료되었습니다.'); window.close();</script>")

    return render(request, 'Main/add_schedule.html', {})

# 아이디 중복 체크 
def isExistsID(request):
    _id = request.POST.get("id")
    s = False
    try:
        User.objects.get(username=_id)
    except Exception:
        s = True
    return HttpResponse(json.dumps({'s' : s,}), content_type="application/json")

def register(request):
    profile_form = RegisterForm()
    profile_form1 = RegisterForm1()
    
    if request.method == 'POST':
        p1 = RegisterForm(request.POST, request.FILES)
        p2 = RegisterForm1(request.POST)
         
        if p2.is_valid() and p1.is_valid():
            rank = p1.cleaned_data['p_rank']
            i = p2.save()
            j = p1.save() # form의 save의 결과는 디폴트는 instance가 반환되는 것을 활용
            if rank == '재학생':
                j.p_rank_pic = RankPicture.objects.get(r_rankcode=2)
            elif rank == '실장':
                j.p_rank_pic = RankPicture.objects.get(r_rankcode=1)
            else:
                j.p_rank_pic = RankPicture.objects.get(r_rankcode=3)
            j.p_user = i
            j.save(update_fields=['p_user', 'p_rank_pic'])
            return redirect('/')
    
    return render(request, 'Main/register.html', {
        'f1' : profile_form, 
        'f2' : profile_form1,
 
    })

def guestbook(request):
    obj = GuestBook.objects.all().order_by('-g_date')
    return render(request, 'Main/guestbook.html', {
        'obj' : obj[:3],
        'totalcnt' : int(obj.__len__()/3)
    })

def ajaxguestbook(request):
    msg = True
    page = int(request.POST.get('page'))
    gb= GuestBook.objects.all().order_by('-g_date')[page+3:page+6]
    gb_datas = {}
    if not gb:
        msg = False
    else:
        for item in gb:
            gb_datas[item.id] = {
                'g_name' : item.g_name,
                'g_content' : item.g_content,
                'g_title' : item.g_title,
                'g_email' : item.g_email
            }
    datas = {
        'gb' : gb_datas,
        'status' : msg
    }
    return HttpResponse(json.dumps(datas), content_type="application/json")

def guestbookWrite(request):
    from datetime import datetime
    hxff = request.META.get('HTTP_X_FORWARDED_FOR')
    if hxff:
        ip = hxff.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')

    datas = {
        'g_name' : request.POST.get('name'),
        'g_content' : request.POST.get('message'),
        'g_title' : request.POST.get('subject'),
        'g_email' : request.POST.get('email'),
        'g_ip' : ip
    }

    GuestBook.objects.create(
        **datas
    )

    return redirect('/guestbook/')

Embedded/Main/templates/Main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
    <title>임베디드 연구실 홈페이지</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Great+Vibes&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Main/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'Main/css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'Main/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'Main/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'Main/css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'Main/css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'Main/css/ionicons.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'Main/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'Main/css/icomoon.css'%}">
    <link rel="stylesheet" href="{% static 'Main/css/style.css'%}">
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>
    </head>
    <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">  
        <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
            <div class="container">
            <a class="navbar-brand" href="{% url 'main:main' %}">E&SW</a>
            <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> Menu
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav nav ml-auto">
                <li class="nav-item"><a href="{% url 'main:main'%}" class="nav-link"><span>홈</span></a></li>
                
                <li class="nav-item"><a href="{% url 'main:Viewmembers' %}" class="nav-link"><span>연구원</span></a></li>
                <li class="nav-item"><a href="{% url 'main:board' %}" class="nav-link"><span>게시판</span></a></li>
                <li class="nav-item"><a href="{% url 'main:guestbook' %}" class="nav-link"><span>방명록</span></a></li>
                {% if not user.is_authenticated %}
                  <li class="nav-item"><a href="{% url 'main:register' %}" class="nav-link"><span>회원가입</span></a></li>
                  <li class="nav-item"><a href="{% url 'main:login' %}" class="nav-link"><span>로그인</span></a></li>
                {% else %}
                  <li class="nav-item"><a href="{% url 'main:logout' %}" class="nav-link"><span>로그아웃</span></a></li>
                  <li id="user_info" class="nav-item"><a href="{% url 'main:mypage' %}" target="_blank" class="nav-link"><span>{{request.user.profile.p_name}}님</span></a></li>
                  
                {% endif %}



    </div>
  </div>
</div>
                
                </ul>
            </div>

            </div>
        </nav>
     
    {% block content %}
    {% endblock %}

    <!---->
     <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2 logo"><span>Embedded & Software</span> Labs</h2>
              <p>연구실</p>
              
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="{% url 'main:Viewmembers' %}" class="py-1 d-block"><span class="glyphicon glyphicon-exclamation-sign"></span>연구원</a></li>
                <li><a href="https://www.cju.ac.kr/www/index.do" class="py-1 d-block"><span class="glyphicon glyphicon-exclamation-sign"></span>청주대학교 홈페이지</a></li>
                <li><a href="https://portal.cju.ac.kr/" class="py-1 d-block"><span class="glyphicon glyphicon-exclamation-sign"></span>청주대학교 포털</a></li>
               

              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Address</h2>
              <ul class="list-unstyled">
               <span>[28503] 충청북도 청주시 청원구 대성로 298 이공대학 07-303호</span>
               
              </ul>
            </div>
          </div>
          
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | <i class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></i> by E&SW</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>


    </footer>
    
    <script src="{% static 'Main/js/jquery.min.js'%}"></script>
    <script src="{% static 'Main/js/jquery-migrate-3.0.1.min.js'%}"></script>
    <script src="{% static 'Main/js/popper.min.js'%}"></script>
    <script src="{% static 'Main/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'Main/js/jquery.easing.1.3.js'%}"></script>
    <script src="{% static 'Main/js/jquery.waypoints.min.js'%}"></script>
    <script src="{% static 'Main/js/jquery.stellar.min.js'%}"></script>
    <script src="{% static 'Main/js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'Main/js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'Main/js/aos.js'%}"></script>
    <script src="{% static 'Main/js/jquery.animateNumber.min.js'%}"></script>
    <script src="{% static 'Main/js/scrollax.min.js'%}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'Main/js/google-map.js'%}"></script>
    <script src="{% static 'Main/js/main.js'%}"></script>
    
    </body>
</html>

Embedded/Main/templates/Main/board.html
{% extends 'Main/base.html' %}
{% block content %}
<section class="ftco-intro img" id="events-section">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
        </div>
    </div>
</section>
<section class="ftco-section bg-light">
<div class="container mt-3 mb-3">
<table class="table table-sm table-hover text-center" style="color : black;">
    <thead class="thead thead-light">
        <th>번호</th>
        <th>분류</th>
        <th>제목</th>
        <th>작성자</th>
        <th>날짜</th>
    </thead>
    <tbody>
    {% for item in notice %}
       <tr class="font-weight-bold" style="background-color : rgb(255, 254, 205)">
                <td style="width : 10%">{{item.id}}</td>
                <td style="width : 10%">{{item.get_b_category_display}}</td>
                <td style="width : 40%" class="text-left"><a style="color : black" href="{% url 'main:read-board' item.id %}">{{item.b_title}}</a></td>
                <td style="width : 10%">{{item.b_user}}</td>
                <td style="width : 30%">{{item.b_date}}</td>
        </tr>
    {% endfor %}
    {% if boards %}
        {% for item in boards %}
            <tr>
        
                <td style="width : 10%">{{item.id}}</td>
                <td style="width : 10%">{{item.get_b_category_display}}</td>
                <td style="width : 50%" class="text-left"><a style="color : black" href="{% url 'main:read-board' item.id %}">{{item.b_title}}</a></td>
                <td style="width : 10%">{% if item.b_user.profile.p_rank_pic.r_images  %} <img src="{{item.b_user.profile.p_rank_pic.r_images.url}}" width="15" height="15"> {% else %} <img src="" width="15" height="15"> {% endif %} {{item.b_user.profile.p_name}}</td>
                <td style="width : 30%">{{item.b_date}}</td>
            </tr>
        {% endfor %}
      {% else %}
        <td colspan="4">게시글이 없습니다. </td>
      {% endif %}
    </tbody>
</table>

    <input type="button" class="btn btn-outline-primary waves-effect" value="글쓰기" onclick="window.location.href='/board/write/'">
</div>
</div>
<!--검색 시-->
{% if p %}
<ul class="pagination pg-blue justify-content-center">
  {% if p.has_previous %}
    <a class="page-link" href="?keyword={{keyword}}&page={{ p.previous_page_number }}">이전</a>
  {% endif %}

  {% if p.has_next %}
    <a class="page-link" href="?keyword={{keyword}}&page={{ p.next_page_number }}">다음</a>
  {% endif %}
 </ul>
  
{% endif %}

{% if is_paginated %}
  <ul class="pagination  pg-blue justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled page-link"><span>&laquo;</span></li>
    {% endif %}
    
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active  page-link"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled page-link"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</nav>
{% endif %}

<div class="container">
  <div class="d-flex justify-content-center">
    <form method="GET" action="{% url 'main:search-board' %}">
    
      <span style="color : black">검색:<span>
      <input name="keyword" placeholder="작성자 이름, 제목" type="text">
      <input type="submit" class="ml-2 btn btn-outline-success waves-effect" value="검색"> 
    </form>
  </div>
</div>
<div>
</section>

{% endblock %}